### ISSUE TITLE
Error Message while compiling

### ISSUE THREAD

**Issue by MigZ1** [MigZ1/LOOT#6]
Arduino: 1.6.9 (Windows 7), Board: "Arduino Leonardo"

sketch\game.cpp: In member function 'void Game::step()':

game.cpp:78: error: 'class System' has no member named 'setCursor'

```
   ab->setCursor(66,2);

       ^
```

game.cpp:79: error: 'class System' has no member named 'print'

```
   ab->print(F("Battle"));

       ^
```

game.cpp:80: error: 'class System' has no member named 'setCursor'

```
   ab->setCursor(66,10);

       ^
```

game.cpp:81: error: 'class System' has no member named 'print'

```
   ab->print(F("goes here!"));

       ^
```

exit status 1
'class System' has no member named 'setCursor'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by spacebruce** [comment]
Oh whoops, I've been working with an outdated version of the arduboy library. Hang on, I'll upgrade and fix.

**Comment by spacebruce** [comment]
Seems they've removed the text functions and moved them to another file. That's weird.

**Comment by spacebruce** [comment]
For the moment, I'm going to leave it as it is, it currently compiles fine using the library from the arduboy site and the arduino library manager, which most people will probably be using, and adapting the current code to work with the current github version will be ... awkward. 
I'll fix it up in time for release and write up some compile instructions.

**Comment by MigZ1** [comment]
Got it to run using older library, works great seeing the chest in!
